### ISSUE TITLE
images missing from Val2014 genLMDB.py

### ISSUE THREAD

**Issue by salvador-blanco** [ZheC/Realtime_Multi-Person_Pose_Estimation#155]
I already fixed the paths as in [1](https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/issues/70) [2](https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/issues/94l) , or at least I think so. Still I have the 
`AttributeError: 'NoType' object has no attribute 'shape'`
Error

I thought It was another path problem, but after printing a lot of stuff I discovered that the path was correct. But the image that the code tries to retrive doesn't exist. 
`/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/val2014/COCO_val2014_000000160840.jpg
`
Every time I run the genLMDB.py the image that does not exist is different 

`/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/val2014/COCO_val2014_000000288685.jpg`

`/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/val2014/COCO_val2014_000000130663.jpg`

Compleate loog:
```
(caffetmp) chava@VC82620v4:~/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training$ python genLMDB.py
COCO
126395
121522
/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/train2014/COCO_train2014_000000268835.jpg
('Miau_imgPath: ', u'/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/train2014/COCO_train2014_000000268835.jpg')
('img_type: ', <type 'numpy.ndarray'>, ' meta_data_type: ', <type 'numpy.ndarray'>, ' mask_miss_type: ', <type 'numpy.ndarray'>, ' img_mask_all: ', <type 'numpy.ndarray'>)
(6, 480, 640)
0/0/39373/126395
/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/train2014/COCO_train2014_000000319521.jpg
('Miau_imgPath: ', u'/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/train2014/COCO_train2014_000000319521.jpg')
('img_type: ', <type 'numpy.ndarray'>, ' meta_data_type: ', <type 'numpy.ndarray'>, ' mask_miss_type: ', <type 'numpy.ndarray'>, ' img_mask_all: ', <type 'numpy.ndarray'>)
(6, 539, 640)
1/1/46936/126395
2/89801 skipped
/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/train2014/COCO_train2014_000000156593.jpg
('Miau_imgPath: ', u'/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/train2014/COCO_train2014_000000156593.jpg')
('img_type: ', <type 'numpy.ndarray'>, ' meta_data_type: ', <type 'numpy.ndarray'>, ' mask_miss_type: ', <type 'numpy.ndarray'>, ' img_mask_all: ', <type 'numpy.ndarray'>)
(6, 427, 640)
3/2/23471/126395
/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/train2014/COCO_train2014_000000164040.jpg
('Miau_imgPath: ', u'/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/train2014/COCO_train2014_000000164040.jpg')
('img_type: ', <type 'numpy.ndarray'>, ' meta_data_type: ', <type 'numpy.ndarray'>, ' mask_miss_type: ', <type 'numpy.ndarray'>, ' img_mask_all: ', <type 'numpy.ndarray'>)
(6, 360, 640)
4/3/24472/126395
/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/train2014/COCO_train2014_000000493446.jpg
('Miau_imgPath: ', u'/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/train2014/COCO_train2014_000000493446.jpg')
('img_type: ', <type 'numpy.ndarray'>, ' meta_data_type: ', <type 'numpy.ndarray'>, ' mask_miss_type: ', <type 'numpy.ndarray'>, ' img_mask_all: ', <type 'numpy.ndarray'>)
(6, 396, 640)
5/4/72879/126395
/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/val2014/COCO_val2014_000000160840.jpg
('Miau_imgPath: ', u'/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/val2014/COCO_val2014_000000160840.jpg')
Traceback (most recent call last):
  File "genLMDB.py", line 204, in <module>
    writeLMDB(['COCO'], '/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/lmdb', 1)
  File "genLMDB.py", line 87, in writeLMDB
    height = img.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by salvador-blanco** [comment]
The solution was just to download again the COCO_val2014
I don't know how pictures disappeared or were not downloaded in the first place. strange
