### ISSUE TITLE
Several errors running genLMDB.py

### ISSUE THREAD

**Issue by salvador-blanco** [ZheC/Realtime_Multi-Person_Pose_Estimation#156]
After some time running the genLMDB.py it stops. I have no idea what is happening
I hope someone can help me

I run the genLMDB.py and it works for a while until one of the following errors pops:

1.- `lmdb.PageNotFoundError: mdb_put: MDB_PAGE_NOTFOUND: Requested page not found`

2.- `lmdb.CorruptedError: mdb_put: MDB_CORRUPTED: Located page was wrong type`

3.- `Aborted (core dumped)`

4.- `lmdb.Error: mdb_txn_commit: Input/output error`

I rerun the genLMDB.py until the next error pops out. Which happens every 1~5 minutes 
(Update I am stock with the last errror)
Here is the terminal log:

1.-
```
1032/1000/126272/126395
/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/train2014/COCO_train2014_000000106978.jpg
('Miau_imgPath: ', u'/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/train2014/COCO_train2014_000000106978.jpg')
('img_type: ', <type 'numpy.ndarray'>, ' meta_data_type: ', <type 'numpy.ndarray'>, ' mask_miss_type: ', <type 'numpy.ndarray'>, ' img_mask_all: ', <type 'numpy.ndarray'>)
(6, 480, 640)
Traceback (most recent call last):
  File "genLMDB.py", line 204, in <module>
    writeLMDB(['COCO'], '/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/lmdb', 1)
  File "genLMDB.py", line 187, in writeLMDB
    txn.put(key, datum.SerializeToString())
lmdb.PageNotFoundError: mdb_put: MDB_PAGE_NOTFOUND: Requested page not found
```
2.-
```
2080/2000/108461/126395
/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/train2014/COCO_train2014_000000238589.jpg
('Miau_imgPath: ', u'/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/train2014/COCO_train2014_000000238589.jpg')
('img_type: ', <type 'numpy.ndarray'>, ' meta_data_type: ', <type 'numpy.ndarray'>, ' mask_miss_type: ', <type 'numpy.ndarray'>, ' img_mask_all: ', <type 'numpy.ndarray'>)
(6, 478, 640)
Traceback (most recent call last):
  File "genLMDB.py", line 205, in <module>
    writeLMDB(['COCO'], '/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/lmdb', 1)
  File "genLMDB.py", line 188, in writeLMDB
    txn.put(key, datum.SerializeToString())
lmdb.CorruptedError: mdb_put: MDB_CORRUPTED: Located page was wrong type
```
3.-
```
3/3/67528/126395
4/88220 skipped
/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/train2014/COCO_train2014_000000255614.jpg
('Miau_imgPath: ', u'/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/train2014/COCO_train2014_000000255614.jpg')
('img_type: ', <type 'numpy.ndarray'>, ' meta_data_type: ', <type 'numpy.ndarray'>, ' mask_miss_type: ', <type 'numpy.ndarray'>, ' img_mask_all: ', <type 'numpy.ndarray'>)
(6, 427, 640)
lib/mdb.c:5497: Assertion 'x > 1' failed in mdb_ovpage_free()
Aborted (core dumped)
```
4.-
```
(caffetmp) chava@VC82620v4:~/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training$ python genLMDB.py
COCO
126395
121522
/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/val2014/COCO_val2014_000000273909.jpg
('Miau_imgPath: ', u'/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/val2014/COCO_val2014_000000273909.jpg')
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
('img_type: ', <type 'numpy.ndarray'>, ' meta_data_type: ', <type 'numpy.ndarray'>, ' mask_miss_type: ', <type 'numpy.ndarray'>, ' img_mask_all: ', <type 'numpy.ndarray'>)
(6, 425, 640)
Traceback (most recent call last):
  File "genLMDB.py", line 207, in <module>
    writeLMDB(['COCO'], '/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/lmdb', 1)
  File "genLMDB.py", line 192, in writeLMDB
    txn.commit()
lmdb.Error: mdb_txn_commit: Input/output error
```

**Comment by salvador-blanco** [comment]
I continue geting similar errors when runing the genLMDB.py
```
2080/2000/108461/126395
/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/train2014/COCO_train2014_000000238589.jpg
('Miau_imgPath: ', u'/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/train2014/COCO_train2014_000000238589.jpg')
('img_type: ', <type 'numpy.ndarray'>, ' meta_data_type: ', <type 'numpy.ndarray'>, ' mask_miss_type: ', <type 'numpy.ndarray'>, ' img_mask_all: ', <type 'numpy.ndarray'>)
(6, 478, 640)
Traceback (most recent call last):
  File "genLMDB.py", line 205, in <module>
    writeLMDB(['COCO'], '/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/lmdb', 1)
  File "genLMDB.py", line 188, in writeLMDB
    txn.put(key, datum.SerializeToString())
lmdb.CorruptedError: mdb_put: MDB_CORRUPTED: Located page was wrong type
```

**Comment by salvador-blanco** [comment]
3/3/67528/126395
4/88220 skipped
/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/train2014/COCO_train2014_000000255614.jpg
('Miau_imgPath: ', u'/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/train2014/COCO_train2014_000000255614.jpg')
('img_type: ', <type 'numpy.ndarray'>, ' meta_data_type: ', <type 'numpy.ndarray'>, ' mask_miss_type: ', <type 'numpy.ndarray'>, ' img_mask_all: ', <type 'numpy.ndarray'>)
(6, 427, 640)
lib/mdb.c:5497: Assertion 'x > 1' failed in mdb_ovpage_free()
Aborted (core dumped)

**Comment by salvador-blanco** [comment]
I still don't know what caused the error, but I tried in other computer and I was able to succeed

**Comment by s1234s030** [comment]
Your dataset and the running script must be on the same computer.

**Comment by BeauDoggie** [comment]
您好！，来信收到，尽快给您回复。
