### ISSUE TITLE
When run genLMDB.py...

### ISSUE THREAD

**Issue by ybai62868** [ZheC/Realtime_Multi-Person_Pose_Estimation#186]
When I run the genLMDB.py, it created two files in /home/users/yang.bai/COCO_kpt/lmdb/
one name is lock.mdb, which is 8 KB. The other one is data.mdb,which is 143660540 KB.

The code run has run for a long time...
But the code got wrong, and the code was stopped.
Traceback (most recent call last):
  File "genLMDB.py", line 195, in <module>
    writeLMDB(['COCO'],'/home/users/yang.bai/COCO_kpt/lmdb',1)
  File "genLMDB.py", line 179, in writeLMDB
    txn.commit()
lmdb.Error: mdb_txn_commit: Input/output error

I want to know whether the code has finished running. And what are the correct result of genLMDB.
Thank you.

**Comment by ybai62868** [comment]
This problem is solved, because my disk have no space for the generated LMDB.
